### PR TITLE
ci: github actions

### PR DESCRIPTION
**Pull request by soullivaneuh**
# Summary

Travis CI replacement.

Details: https://github.com/Algatux/influxdb-bundle/pull/98#issuecomment-1916970326

### CODE REVIEW

**Comment by soullivaneuh** [comment]
@Algatux I did a setup with a matrix similar to the old Travis CI configuration and we have a lot of failures... do you remember the state of the previous Travis CI run? :thinking:

**Comment by soullivaneuh** [comment]
@Algatux I did find a way to make it working, but I had to remove the SF v3 support. I think it is acceptable according to the age of this release... Also it respect the semver rules What do you think?

**Comment by soullivaneuh** [comment]
I'll start with that to start the PHP8 compatibility work. It may be adjusted in the meantime.

**Comment by Algatux** [comment]
@soullivaneuh sorry to be late, thanks for all the work you are doing. Anyway yep I agree with the removal of symfony v3 as a supported version

**Pull request merged**
