### PR TITLE
Deprecate PointsCollection class

### LINKED ISSUE #15: The goal of PointCollection
What is the goal of `PointCollection` The implementation looks superfluous IMHO.

From your doc, you have to do this:

``` php
$time = new \DateTime();

$points = new PointsCollection([new Point(
    'test_metric', // name of the measurement
    0.64, // the measurement value
    ['host' => 'server01', 'region' => 'italy'], // optional tags
    ['cpucount' => rand(1,100), 'memory' => memory_get_usage(true)], // optional additional fields
    $time->getTimestamp()
)],Database::PRECISION_SECONDS);

$container
    ->get('algatux_influx_db.client.http.writer_client')
    ->write($points);
```

But from [influxdb-php documentation](https://github.com/influxdata/influxdb-php#writing-data):

``` php
// create an array of points
$points = array(
    new Point(
        'test_metric', // name of the measurement
        0.64, // the measurement value
        ['host' => 'server01', 'region' => 'us-west'], // optional tags
        ['cpucount' => 10], // optional additional fields
        1435255849 // Time precision has to be set to seconds!
    ),
    new Point(
        'test_metric', // name of the measurement
        0.84, // the measurement value
        ['host' => 'server01', 'region' => 'us-west'], // optional tags
        ['cpucount' => 10], // optional additional fields
        1435255849 // Time precision has to be set to seconds!
    )
);

// we are writing unix timestamps, which have a second precision
$result = $database->writePoints($points, Database::PRECISION_SECONDS);
```

This is basically the same.

Plus, since #10, we will directly get an access to the `Database` instance. So `PointCollection` would not be used at all.

What do you think?

### PR DESCRIPTION
**Pull request by soullivaneuh**
Closes #15

### CODE REVIEW

**Comment by Algatux** [comment]
Not sure about deprecating it, can't this class become a simple value object removing ArrayCollection parent ?

**Comment by soullivaneuh** [comment]
Please read again my comment: https://github.com/Algatux/influxdb-bundle/issues/15#issuecomment-223574274 :-)

The goal is not to reinvent the wheel with providing an `ArrayCollection` copy, but remove this class on next major to let the user the choice of which implementation he wants (`ArrayCollection`) or other.

**Comment by soullivaneuh** [comment]
Note: This is the last PR that can be integrated before tagging the 1.1.0 release and create a 1.x branch. :+1:

**Comment by Algatux** [comment]
> The goal is not to reinvent the wheel with providing an ArrayCollection copy, but remove this class on next major to let the user the choice of which implementation he wants (ArrayCollection) or other.

not exactly what I had in mind but i surrender, an additional object is actually unecessary

**Pull request merged**
