### PR TITLE
Make udp optional

### LINKED ISSUE #36: Make udp optionals
Currently, both http and upd client/database instances are created, even if we don't needed.

Maybe we could make it optional with the config:

``` yaml
influx_db:
    connections:
        telegraf:
            host: '%influxdb_host%'
            database: '%influxdb_telegraf_db%'
            udp: false # Disable UDP
```

Both `udp` and `http` port would be `false` by default and a configuration validation could check if at least one of them is enabled.

Edit: Only udp will be optional: https://github.com/Algatux/influxdb-bundle/issues/36#issuecomment-223899498

What do you think?

### PR DESCRIPTION
**Pull request by soullivaneuh**
Closes #36.
- [x] Make UDP optional
- [x] Throw exception on listener if UDP is not available

### CODE REVIEW

**Comment by soullivaneuh** [comment]
@Algatux The PR is ready.

For me, it's the last feature I would like to push before 2.0.0.

Release is coming! :tada: :wink:

**Comment by Algatux** [comment]
Great work! u pratically did all the work ! :+1:

**Comment by soullivaneuh** [comment]
@Algatux Thanks! :-)

Any ETA for the 2.0 release?

**Comment by Algatux** [comment]
I ll take a look this evening

**Pull request merged**
