### PR TITLE
Allow Symfony 2.8

### PR DESCRIPTION
**Pull request by soullivaneuh**
Symfony 2.8 IS the same as 3.0, but with the deprecated old feature.

This was done to provide an easy upgrading way between 2.x and 3.x.

Lot of people are still on 2.x version of Symfony.

Nothing has to be changed on the project codebase.

Plus, this is a LTS version. It's important to keep support on it.

Ref: http://symfony.com/blog/transition-from-symfony-2-7-to-3-0-symfony-2-8-on-its-way

Note I also removed the `composer.lock` file and replaced `composer install` by `composer update`.

As a library, dependencies tests should not be locked at all.

Travis was update to test multiple Symfony versions so you will have the proof that your bundle is compatible. :+1:

### CODE REVIEW

**Comment by gallart** [comment]
👍

**Comment by soullivaneuh** [comment]
https://travis-ci.org/Algatux/influxdb-bundle/jobs/134418403#L171

Seems some of your dependencies are not compatible with Symfony 3.1.

Shall I remove this part?

Related issue: https://github.com/phpspec/prophecy/issues/272
Related PR: https://github.com/phpspec/prophecy/pull/275

**Comment by Algatux** [comment]
Hi thanks a lot for your pr. I will take a look as soon as possible.

Yes please remove symfony 3.1 for now.

**Comment by soullivaneuh** [comment]
@Algatux done! :+1:

**Comment by soullivaneuh** [comment]
Thanks you for the merge! :+1: 

Could you please tag a new release for that?

**Comment by soullivaneuh** [comment]
@Algatux I saw you did a merge by Squash. This is your choice, but I advice you to not do this if the PR contains multiple commits. In this case, each commit was about a specific subject. :wink: 

cc @greg0ire

**Comment by greg0ire** [comment]
Those beautiful, verified commits… squashed…
so sad

**Comment by Algatux** [comment]
@Soullivaneuh @greg0ire sorry for the squash guys! I was verry excited for the PR 😇

**Pull request merged**
