### PR TITLE
Add support for php 8

### PR DESCRIPTION
**Pull request by artem-yakymchuk-paysera**

### CODE REVIEW

**Comment by Algatux** [comment]
Hello @artem-yakymchuk-paysera ! I checked manually the dependencies and seems that they will be ok switching to php8. Unfortunately the CI is not working anymore and must be ported from travis-ci (they will need some love). We can merge it but i'm not sure about creating a tag.

**Comment by soullivaneuh** [comment]
> Unfortunately the CI is not working anymore and must be ported from travis-ci (they will need some love)

@Algatux I am not sure of what you mean by "be ported from travis-ci". Do you mean using GitHub actions instead of this service?

According to your answer I may manage that if I have enough right on this repository, and do the failing tests cleanup reported in https://github.com/Algatux/influxdb-bundle/pull/92#issuecomment-609420066

BTW, according to the semver convention, dropping a dependency version support is not a breaking change. As 3.0.0-beta is already out, let's going with it, but I suggest to strictly apply this convention in the future. Do we agree with that?

**Comment by Algatux** [comment]
@soullivaneuh yes meant exactly a "port" to GitHub actions. 

If you have time to do so you are welcome! (sorry but I do not have anymore time to follow this project). As collaborator you should already be able to manage the repo, if not please let me know.

Regarding appling semver more strictly I completely agree, that beta version must be considered and error/exception to the rule.

Thanks in advance for the support

**Comment by soullivaneuh** [comment]
Closing in favor of #100. A bit of adaptation had to be done on the bundle class definition.

**Pull request closed without merging**
