### PR TITLE
Travis improvements

### PR DESCRIPTION
**Pull request by soullivaneuh**
All propositions are explained on commit titles and comments.

Feel free to comment if you want to change something. :+1: 

EDIT: I recommend you to create a private token for GitHub API. No special rights needed.

Then, add it to `GITHUB_OAUTH_TOKEN` env var on Travis config.

Make this variable private so this will not be exported on PR jobs, only branches.

I would like to remove phpunit from dependencies and download it directly but it seems you need it because of dependencies issues...

### CODE REVIEW

**Comment by Algatux** [comment]
@Soullivaneuh I will squash this! all travis.yml related

**Comment by greg0ire** [comment]
>  I will squash this!

omg 

Why would you do that? You're basically making one big unreadable commit out of 10 small beautiful commits… Are you trying to save disk space ?

**Comment by Algatux** [comment]
@greg0ire were all micro commits on a single file that in practise has been rewrited. The question is. Why separate them.

**Comment by greg0ire** [comment]
> Why separate them.

Because they are about different concerns. If you fix a typo and you add a new method you do two commits : that way if the method turns out to be useless, you can revert it without reverting the typo too. Or if you use git bisect, and bisect a bug down to a commit, you would like the commit to have a diff as small as possible, and a better message than : "changed 1000 things in file.php, here is the list, guess which one introduces the bug you are looking for"… just because it is in the same file doesn't mean it is related.

Let's do a simple experiment : click on the "changed" tab, and look at the diff. Can you say what was changed without forgetting anything? Now click the "all commits" select box, and select the first commit. Look at the diff. What changed is now obvious, and you have a matching commit message that explains what happened, so your history is usable, you can easily make sense out of it.

**Comment by Algatux** [comment]
I actually don't think this was the case. Sorry that a squash caused you so much sadness.

**Comment by greg0ire** [comment]
> I actually don't think this was the case.

You mean you can tell exactly what happened from the whole diff?

> Sorry that a squash caused you so much sadness.

Don't worry, I'll get over it at some point, these are not my commits ;)

**Comment by soullivaneuh** [comment]
> these are not my commits ;)

These are mine. :broken_heart: :stuck_out_tongue:

**Pull request merged**
